-- ===============================================
-- SEED RESOURCES TABLE
-- Date: 2025-11-20
-- Purpose: Populate resources table with 38 strategic assets
-- Source: dev/resource-library/RESOURCE_ASSET_MAPPING.json
-- Auto-generated by: scripts/generate-seed-migration.js
-- ===============================================

-- Asset 1: ICP Analysis Framework
INSERT INTO resources (
  resource_code, asset_number, name, description, tier,
  strategic_prompts, implementation_guides,
  generation_time_minutes, consulting_equivalent_usd,
  requires_context_from, personalization_depth,
  unlock_milestone_code, unlock_threshold_percentage,
  display_order, is_active
) VALUES (
  'asset-1-icp-analysis',
  1,
  'ICP Analysis Framework',
  'Define your ideal customer with surgical precision',
  'foundation',
  '["icp-analysis"]'::jsonb,
  '["icp-crm-qualification-checklist","icp-customer-validation","icp-rating-calibration"]'::jsonb,
  12,
  10000,
  ARRAY[]::TEXT[],
  1, -- Personalization depth = asset number
  'sub_9_1',
  25,
  1,
  true
);

-- Asset 2: Target Buyer Personas
INSERT INTO resources (
  resource_code, asset_number, name, description, tier,
  strategic_prompts, implementation_guides,
  generation_time_minutes, consulting_equivalent_usd,
  requires_context_from, personalization_depth,
  unlock_milestone_code, unlock_threshold_percentage,
  display_order, is_active
) VALUES (
  'asset-2-target-buyer-personas',
  2,
  'Target Buyer Personas',
  'Detailed profiles of decision makers and influencers',
  'foundation',
  '["target-buyer-personas"]'::jsonb,
  '["persona-sales-messaging","buyer-persona-rating-training","empathy-discovery-script"]'::jsonb,
  12,
  8000,
  ARRAY['asset-1-icp-analysis']::TEXT[],
  2, -- Personalization depth = asset number
  'sub_9_1',
  50,
  2,
  true
);

-- Asset 3: Empathy Maps
INSERT INTO resources (
  resource_code, asset_number, name, description, tier,
  strategic_prompts, implementation_guides,
  generation_time_minutes, consulting_equivalent_usd,
  requires_context_from, personalization_depth,
  unlock_milestone_code, unlock_threshold_percentage,
  display_order, is_active
) VALUES (
  'asset-3-empathy-maps',
  3,
  'Empathy Maps',
  'Deep buyer psychology and emotional drivers',
  'foundation',
  '["empathy-maps"]'::jsonb,
  '["content-strategy-from-empathy","discovery-questions-update"]'::jsonb,
  10,
  7000,
  ARRAY['asset-1-icp-analysis', 'asset-2-target-buyer-personas']::TEXT[],
  3, -- Personalization depth = asset number
  'sub_9_1',
  75,
  3,
  true
);

-- Asset 4: ICP Rating System
INSERT INTO resources (
  resource_code, asset_number, name, description, tier,
  strategic_prompts, implementation_guides,
  generation_time_minutes, consulting_equivalent_usd,
  requires_context_from, personalization_depth,
  unlock_milestone_code, unlock_threshold_percentage,
  display_order, is_active
) VALUES (
  'asset-4-icp-rating-system',
  4,
  'ICP Rating System',
  'Quantify customer fit with systematic scoring',
  'foundation',
  '["icp-rating-system"]'::jsonb,
  '["icp-crm-implementation","icp-calibration-with-customers"]'::jsonb,
  10,
  6000,
  ARRAY['asset-1-icp-analysis', 'asset-2-target-buyer-personas', 'asset-3-empathy-maps']::TEXT[],
  4, -- Personalization depth = asset number
  'sub_9_1',
  100,
  4,
  true
);

-- Asset 5: Buyer Persona Rating
INSERT INTO resources (
  resource_code, asset_number, name, description, tier,
  strategic_prompts, implementation_guides,
  generation_time_minutes, consulting_equivalent_usd,
  requires_context_from, personalization_depth,
  unlock_milestone_code, unlock_threshold_percentage,
  display_order, is_active
) VALUES (
  'asset-5-buyer-persona-rating',
  5,
  'Buyer Persona Rating',
  'Score individual contacts against persona criteria',
  'foundation',
  '["buyer-persona-rating"]'::jsonb,
  '["contact-scoring-workflow","sales-team-training"]'::jsonb,
  10,
  5000,
  ARRAY['asset-1-icp-analysis', 'asset-2-target-buyer-personas', 'asset-3-empathy-maps', 'asset-4-icp-rating-system']::TEXT[],
  5, -- Personalization depth = asset number
  'sub_9_2',
  25,
  5,
  true
);

-- Asset 6: Negative Buyer Personas
INSERT INTO resources (
  resource_code, asset_number, name, description, tier,
  strategic_prompts, implementation_guides,
  generation_time_minutes, consulting_equivalent_usd,
  requires_context_from, personalization_depth,
  unlock_milestone_code, unlock_threshold_percentage,
  display_order, is_active
) VALUES (
  'asset-6-negative-buyer-personas',
  6,
  'Negative Buyer Personas',
  'Identify and avoid poor-fit customers systematically',
  'foundation',
  '["negative-buyer-personas","non-ideal-customer-profile"]'::jsonb,
  '["crm-disqualification-rules","red-flag-checklist"]'::jsonb,
  12,
  6000,
  ARRAY['asset-1-icp-analysis', 'asset-2-target-buyer-personas', 'asset-3-empathy-maps', 'asset-4-icp-rating-system', 'asset-5-buyer-persona-rating']::TEXT[],
  6, -- Personalization depth = asset number
  'sub_9_2',
  50,
  6,
  true
);

-- Asset 7: Product-Market Fit Assessment
INSERT INTO resources (
  resource_code, asset_number, name, description, tier,
  strategic_prompts, implementation_guides,
  generation_time_minutes, consulting_equivalent_usd,
  requires_context_from, personalization_depth,
  unlock_milestone_code, unlock_threshold_percentage,
  display_order, is_active
) VALUES (
  'asset-7-pmf-assessment',
  7,
  'Product-Market Fit Assessment',
  'Measure and track PMF progression systematically',
  'foundation',
  '["pmf-assessment","pmf-readiness-assessment"]'::jsonb,
  '["prioritized-action-plan","quarterly-review-cadence"]'::jsonb,
  15,
  12000,
  ARRAY['asset-1-icp-analysis', 'asset-2-target-buyer-personas', 'asset-3-empathy-maps', 'asset-4-icp-rating-system', 'asset-5-buyer-persona-rating', 'asset-6-negative-buyer-personas']::TEXT[],
  7, -- Personalization depth = asset number
  'sub_9_2',
  75,
  7,
  true
);

-- Asset 8: Product Potential Assessment
INSERT INTO resources (
  resource_code, asset_number, name, description, tier,
  strategic_prompts, implementation_guides,
  generation_time_minutes, consulting_equivalent_usd,
  requires_context_from, personalization_depth,
  unlock_milestone_code, unlock_threshold_percentage,
  display_order, is_active
) VALUES (
  'asset-8-product-potential-assessment',
  8,
  'Product Potential Assessment',
  'Evaluate market opportunity and competitive positioning',
  'foundation',
  '["product-potential-assessment"]'::jsonb,
  '["competitive-positioning-refinement","roi-calculator-creation"]'::jsonb,
  12,
  10000,
  ARRAY['asset-1-icp-analysis', 'asset-2-target-buyer-personas', 'asset-3-empathy-maps', 'asset-4-icp-rating-system', 'asset-5-buyer-persona-rating', 'asset-6-negative-buyer-personas', 'asset-7-pmf-assessment']::TEXT[],
  8, -- Personalization depth = asset number
  'sub_9_2',
  100,
  8,
  true
);

-- Asset 9: Refined Product Description
INSERT INTO resources (
  resource_code, asset_number, name, description, tier,
  strategic_prompts, implementation_guides,
  generation_time_minutes, consulting_equivalent_usd,
  requires_context_from, personalization_depth,
  unlock_milestone_code, unlock_threshold_percentage,
  display_order, is_active
) VALUES (
  'asset-9-refined-product-description',
  9,
  'Refined Product Description',
  'Crystallize product positioning and value proposition',
  'foundation',
  '["refined-product-description"]'::jsonb,
  '["website-copy-update","one-pager-sales-deck"]'::jsonb,
  10,
  8000,
  ARRAY['asset-1-icp-analysis', 'asset-2-target-buyer-personas', 'asset-3-empathy-maps', 'asset-4-icp-rating-system', 'asset-5-buyer-persona-rating', 'asset-6-negative-buyer-personas', 'asset-7-pmf-assessment', 'asset-8-product-potential-assessment']::TEXT[],
  9, -- Personalization depth = asset number
  'sub_9_3',
  25,
  9,
  true
);

-- Asset 10: Technical Sales Translator
INSERT INTO resources (
  resource_code, asset_number, name, description, tier,
  strategic_prompts, implementation_guides,
  generation_time_minutes, consulting_equivalent_usd,
  requires_context_from, personalization_depth,
  unlock_milestone_code, unlock_threshold_percentage,
  display_order, is_active
) VALUES (
  'asset-10-technical-sales-translator',
  10,
  'Technical Sales Translator',
  'Convert technical features into business outcomes',
  'foundation',
  '["technical-sales-translator"]'::jsonb,
  '["statistics-enhanced-materials","value-messaging-templates","persona-based-messaging"]'::jsonb,
  12,
  9000,
  ARRAY['asset-1-icp-analysis', 'asset-2-target-buyer-personas', 'asset-3-empathy-maps', 'asset-4-icp-rating-system', 'asset-5-buyer-persona-rating', 'asset-6-negative-buyer-personas', 'asset-7-pmf-assessment', 'asset-8-product-potential-assessment', 'asset-9-refined-product-description']::TEXT[],
  10, -- Personalization depth = asset number
  'sub_9_3',
  50,
  10,
  true
);

-- Asset 11: Value Messaging System
INSERT INTO resources (
  resource_code, asset_number, name, description, tier,
  strategic_prompts, implementation_guides,
  generation_time_minutes, consulting_equivalent_usd,
  requires_context_from, personalization_depth,
  unlock_milestone_code, unlock_threshold_percentage,
  display_order, is_active
) VALUES (
  'asset-11-value-messaging',
  11,
  'Value Messaging System',
  'Craft compelling messages that resonate with buyers',
  'foundation',
  '["value-messaging"]'::jsonb,
  '["ab-test-email-templates","seo-strategy"]'::jsonb,
  10,
  7000,
  ARRAY['asset-1-icp-analysis', 'asset-2-target-buyer-personas', 'asset-3-empathy-maps', 'asset-4-icp-rating-system', 'asset-5-buyer-persona-rating', 'asset-6-negative-buyer-personas', 'asset-7-pmf-assessment', 'asset-8-product-potential-assessment', 'asset-9-refined-product-description', 'asset-10-technical-sales-translator']::TEXT[],
  11, -- Personalization depth = asset number
  'sub_9_3',
  75,
  11,
  true
);

-- Asset 12: Cost of Inaction Calculator
INSERT INTO resources (
  resource_code, asset_number, name, description, tier,
  strategic_prompts, implementation_guides,
  generation_time_minutes, consulting_equivalent_usd,
  requires_context_from, personalization_depth,
  unlock_milestone_code, unlock_threshold_percentage,
  display_order, is_active
) VALUES (
  'asset-12-cost-of-inaction-calculator',
  12,
  'Cost of Inaction Calculator',
  'Quantify the business impact of not solving the problem',
  'foundation',
  '["cost-of-inaction-calculator"]'::jsonb,
  '["personalized-one-pagers","urgency-email-sequence"]'::jsonb,
  10,
  8000,
  ARRAY['asset-1-icp-analysis', 'asset-2-target-buyer-personas', 'asset-3-empathy-maps', 'asset-4-icp-rating-system', 'asset-5-buyer-persona-rating', 'asset-6-negative-buyer-personas', 'asset-7-pmf-assessment', 'asset-8-product-potential-assessment', 'asset-9-refined-product-description', 'asset-10-technical-sales-translator', 'asset-11-value-messaging']::TEXT[],
  12, -- Personalization depth = asset number
  'sub_10_1',
  25,
  12,
  true
);

-- Asset 13: Compelling Events Identifier
INSERT INTO resources (
  resource_code, asset_number, name, description, tier,
  strategic_prompts, implementation_guides,
  generation_time_minutes, consulting_equivalent_usd,
  requires_context_from, personalization_depth,
  unlock_milestone_code, unlock_threshold_percentage,
  display_order, is_active
) VALUES (
  'asset-13-compelling-events',
  13,
  'Compelling Events Identifier',
  'Detect buyer urgency triggers and timing signals',
  'foundation',
  '["compelling-events"]'::jsonb,
  '["trigger-based-prospecting-system","event-specific-landing-pages"]'::jsonb,
  10,
  7000,
  ARRAY['asset-1-icp-analysis', 'asset-2-target-buyer-personas', 'asset-3-empathy-maps', 'asset-4-icp-rating-system', 'asset-5-buyer-persona-rating', 'asset-6-negative-buyer-personas', 'asset-7-pmf-assessment', 'asset-8-product-potential-assessment', 'asset-9-refined-product-description', 'asset-10-technical-sales-translator', 'asset-11-value-messaging', 'asset-12-cost-of-inaction-calculator']::TEXT[],
  13, -- Personalization depth = asset number
  'sub_10_1',
  50,
  13,
  true
);

-- Asset 14: Sales Slide Deck Generator
INSERT INTO resources (
  resource_code, asset_number, name, description, tier,
  strategic_prompts, implementation_guides,
  generation_time_minutes, consulting_equivalent_usd,
  requires_context_from, personalization_depth,
  unlock_milestone_code, unlock_threshold_percentage,
  display_order, is_active
) VALUES (
  'asset-14-sales-slide-deck',
  14,
  'Sales Slide Deck Generator',
  'AI-generated presentation customized for your product',
  'foundation',
  '["sales-slide-deck"]'::jsonb,
  '["demo-script-based-on-deck","customization-for-prospects"]'::jsonb,
  15,
  10000,
  ARRAY['asset-1-icp-analysis', 'asset-2-target-buyer-personas', 'asset-3-empathy-maps', 'asset-4-icp-rating-system', 'asset-5-buyer-persona-rating', 'asset-6-negative-buyer-personas', 'asset-7-pmf-assessment', 'asset-8-product-potential-assessment', 'asset-9-refined-product-description', 'asset-10-technical-sales-translator', 'asset-11-value-messaging', 'asset-12-cost-of-inaction-calculator', 'asset-13-compelling-events']::TEXT[],
  14, -- Personalization depth = asset number
  'sub_10_1',
  75,
  14,
  true
);

-- Asset 15: Buying Committee Navigation
INSERT INTO resources (
  resource_code, asset_number, name, description, tier,
  strategic_prompts, implementation_guides,
  generation_time_minutes, consulting_equivalent_usd,
  requires_context_from, personalization_depth,
  unlock_milestone_code, unlock_threshold_percentage,
  display_order, is_active
) VALUES (
  'asset-15-buying-committee-navigation-guide',
  15,
  'Buying Committee Navigation',
  'Map and influence complex B2B buying committees',
  'growth',
  '["buying-committee-navigation-guide"]'::jsonb,
  '["stakeholder-specific-sales-plays","feature-to-kpi-matrix"]'::jsonb,
  12,
  12000,
  ARRAY['asset-1-icp-analysis', 'asset-2-target-buyer-personas', 'asset-3-empathy-maps', 'asset-4-icp-rating-system', 'asset-5-buyer-persona-rating', 'asset-6-negative-buyer-personas', 'asset-7-pmf-assessment', 'asset-8-product-potential-assessment', 'asset-9-refined-product-description', 'asset-10-technical-sales-translator', 'asset-11-value-messaging', 'asset-12-cost-of-inaction-calculator', 'asset-13-compelling-events', 'asset-14-sales-slide-deck']::TEXT[],
  15, -- Personalization depth = asset number
  'sub_10_2',
  25,
  15,
  true
);

-- Asset 16: Stakeholder Arsenal
INSERT INTO resources (
  resource_code, asset_number, name, description, tier,
  strategic_prompts, implementation_guides,
  generation_time_minutes, consulting_equivalent_usd,
  requires_context_from, personalization_depth,
  unlock_milestone_code, unlock_threshold_percentage,
  display_order, is_active
) VALUES (
  'asset-16-stakeholder-arsenal',
  16,
  'Stakeholder Arsenal',
  'Engagement strategies for each buying committee member',
  'growth',
  '["stakeholder-arsenal"]'::jsonb,
  '["engagement-playbooks-per-stakeholder","journey-stage-playbooks"]'::jsonb,
  12,
  11000,
  ARRAY['asset-1-icp-analysis', 'asset-2-target-buyer-personas', 'asset-3-empathy-maps', 'asset-4-icp-rating-system', 'asset-5-buyer-persona-rating', 'asset-6-negative-buyer-personas', 'asset-7-pmf-assessment', 'asset-8-product-potential-assessment', 'asset-9-refined-product-description', 'asset-10-technical-sales-translator', 'asset-11-value-messaging', 'asset-12-cost-of-inaction-calculator', 'asset-13-compelling-events', 'asset-14-sales-slide-deck', 'asset-15-buying-committee-navigation-guide']::TEXT[],
  16, -- Personalization depth = asset number
  'sub_10_2',
  50,
  16,
  true
);

-- Asset 17: Mock Selling Dialogues
INSERT INTO resources (
  resource_code, asset_number, name, description, tier,
  strategic_prompts, implementation_guides,
  generation_time_minutes, consulting_equivalent_usd,
  requires_context_from, personalization_depth,
  unlock_milestone_code, unlock_threshold_percentage,
  display_order, is_active
) VALUES (
  'asset-17-mock-selling-dialogues',
  17,
  'Mock Selling Dialogues',
  'Practice conversations and objection handling',
  'growth',
  '["mock-selling-dialogues"]'::jsonb,
  '["call-analysis-framework","objection-handling-practice"]'::jsonb,
  12,
  9000,
  ARRAY['asset-1-icp-analysis', 'asset-2-target-buyer-personas', 'asset-3-empathy-maps', 'asset-4-icp-rating-system', 'asset-5-buyer-persona-rating', 'asset-6-negative-buyer-personas', 'asset-7-pmf-assessment', 'asset-8-product-potential-assessment', 'asset-9-refined-product-description', 'asset-10-technical-sales-translator', 'asset-11-value-messaging', 'asset-12-cost-of-inaction-calculator', 'asset-13-compelling-events', 'asset-14-sales-slide-deck', 'asset-15-buying-committee-navigation-guide', 'asset-16-stakeholder-arsenal']::TEXT[],
  17, -- Personalization depth = asset number
  'sub_10_2',
  75,
  17,
  true
);

-- Asset 18: Discovery Call Framework
INSERT INTO resources (
  resource_code, asset_number, name, description, tier,
  strategic_prompts, implementation_guides,
  generation_time_minutes, consulting_equivalent_usd,
  requires_context_from, personalization_depth,
  unlock_milestone_code, unlock_threshold_percentage,
  display_order, is_active
) VALUES (
  'asset-18-mock-selling-dialogues',
  18,
  'Discovery Call Framework',
  'Structured approach to customer discovery conversations',
  'growth',
  '["mock-selling-dialogues"]'::jsonb,
  '["call-script","question-bank","recording-analysis"]'::jsonb,
  10,
  8000,
  ARRAY['asset-1-icp-analysis', 'asset-2-target-buyer-personas', 'asset-3-empathy-maps', 'asset-4-icp-rating-system', 'asset-5-buyer-persona-rating', 'asset-6-negative-buyer-personas', 'asset-7-pmf-assessment', 'asset-8-product-potential-assessment', 'asset-9-refined-product-description', 'asset-10-technical-sales-translator', 'asset-11-value-messaging', 'asset-12-cost-of-inaction-calculator', 'asset-13-compelling-events', 'asset-14-sales-slide-deck', 'asset-15-buying-committee-navigation-guide', 'asset-16-stakeholder-arsenal', 'asset-17-mock-selling-dialogues']::TEXT[],
  18, -- Personalization depth = asset number
  'sub_10_3',
  25,
  18,
  true
);

-- Asset 19: Day-in-Life Scenarios
INSERT INTO resources (
  resource_code, asset_number, name, description, tier,
  strategic_prompts, implementation_guides,
  generation_time_minutes, consulting_equivalent_usd,
  requires_context_from, personalization_depth,
  unlock_milestone_code, unlock_threshold_percentage,
  display_order, is_active
) VALUES (
  'asset-19-day-in-life',
  19,
  'Day-in-Life Scenarios',
  'Map typical user workflows and touchpoints',
  'growth',
  '["day-in-life"]'::jsonb,
  '["usage-session-analysis","demo-script-from-scenario"]'::jsonb,
  10,
  7000,
  ARRAY['asset-1-icp-analysis', 'asset-2-target-buyer-personas', 'asset-3-empathy-maps', 'asset-4-icp-rating-system', 'asset-5-buyer-persona-rating', 'asset-6-negative-buyer-personas', 'asset-7-pmf-assessment', 'asset-8-product-potential-assessment', 'asset-9-refined-product-description', 'asset-10-technical-sales-translator', 'asset-11-value-messaging', 'asset-12-cost-of-inaction-calculator', 'asset-13-compelling-events', 'asset-14-sales-slide-deck', 'asset-15-buying-committee-navigation-guide', 'asset-16-stakeholder-arsenal', 'asset-17-mock-selling-dialogues', 'asset-18-mock-selling-dialogues']::TEXT[],
  19, -- Personalization depth = asset number
  'sub_11_1',
  25,
  19,
  true
);

-- Asset 20: Month-in-Life Analysis
INSERT INTO resources (
  resource_code, asset_number, name, description, tier,
  strategic_prompts, implementation_guides,
  generation_time_minutes, consulting_equivalent_usd,
  requires_context_from, personalization_depth,
  unlock_milestone_code, unlock_threshold_percentage,
  display_order, is_active
) VALUES (
  'asset-20-month-in-life',
  20,
  'Month-in-Life Analysis',
  'Long-term usage patterns and sustained value delivery',
  'growth',
  '["month-in-life"]'::jsonb,
  '["long-term-usage-patterns","onboarding-sequence-design"]'::jsonb,
  10,
  7000,
  ARRAY['asset-1-icp-analysis', 'asset-2-target-buyer-personas', 'asset-3-empathy-maps', 'asset-4-icp-rating-system', 'asset-5-buyer-persona-rating', 'asset-6-negative-buyer-personas', 'asset-7-pmf-assessment', 'asset-8-product-potential-assessment', 'asset-9-refined-product-description', 'asset-10-technical-sales-translator', 'asset-11-value-messaging', 'asset-12-cost-of-inaction-calculator', 'asset-13-compelling-events', 'asset-14-sales-slide-deck', 'asset-15-buying-committee-navigation-guide', 'asset-16-stakeholder-arsenal', 'asset-17-mock-selling-dialogues', 'asset-18-mock-selling-dialogues', 'asset-19-day-in-life']::TEXT[],
  20, -- Personalization depth = asset number
  'sub_11_1',
  50,
  20,
  true
);

-- Asset 21: User Journey Maps
INSERT INTO resources (
  resource_code, asset_number, name, description, tier,
  strategic_prompts, implementation_guides,
  generation_time_minutes, consulting_equivalent_usd,
  requires_context_from, personalization_depth,
  unlock_milestone_code, unlock_threshold_percentage,
  display_order, is_active
) VALUES (
  'asset-21-user-journey-maps',
  21,
  'User Journey Maps',
  'Visualize customer experience from awareness to advocacy',
  'growth',
  '["user-journey-maps"]'::jsonb,
  '["touchpoint-gap-analysis","stage-specific-content"]'::jsonb,
  12,
  9000,
  ARRAY['asset-1-icp-analysis', 'asset-2-target-buyer-personas', 'asset-3-empathy-maps', 'asset-4-icp-rating-system', 'asset-5-buyer-persona-rating', 'asset-6-negative-buyer-personas', 'asset-7-pmf-assessment', 'asset-8-product-potential-assessment', 'asset-9-refined-product-description', 'asset-10-technical-sales-translator', 'asset-11-value-messaging', 'asset-12-cost-of-inaction-calculator', 'asset-13-compelling-events', 'asset-14-sales-slide-deck', 'asset-15-buying-committee-navigation-guide', 'asset-16-stakeholder-arsenal', 'asset-17-mock-selling-dialogues', 'asset-18-mock-selling-dialogues', 'asset-19-day-in-life', 'asset-20-month-in-life']::TEXT[],
  21, -- Personalization depth = asset number
  'sub_11_1',
  75,
  21,
  true
);

-- Asset 22: Buyer UX Considerations
INSERT INTO resources (
  resource_code, asset_number, name, description, tier,
  strategic_prompts, implementation_guides,
  generation_time_minutes, consulting_equivalent_usd,
  requires_context_from, personalization_depth,
  unlock_milestone_code, unlock_threshold_percentage,
  display_order, is_active
) VALUES (
  'asset-22-buyer-ux-considerations',
  22,
  'Buyer UX Considerations',
  'Optimize product experience for buyer success',
  'growth',
  '["buyer-ux-considerations"]'::jsonb,
  '["ux-prioritization-matrix","usability-testing-plan"]'::jsonb,
  10,
  8000,
  ARRAY['asset-1-icp-analysis', 'asset-2-target-buyer-personas', 'asset-3-empathy-maps', 'asset-4-icp-rating-system', 'asset-5-buyer-persona-rating', 'asset-6-negative-buyer-personas', 'asset-7-pmf-assessment', 'asset-8-product-potential-assessment', 'asset-9-refined-product-description', 'asset-10-technical-sales-translator', 'asset-11-value-messaging', 'asset-12-cost-of-inaction-calculator', 'asset-13-compelling-events', 'asset-14-sales-slide-deck', 'asset-15-buying-committee-navigation-guide', 'asset-16-stakeholder-arsenal', 'asset-17-mock-selling-dialogues', 'asset-18-mock-selling-dialogues', 'asset-19-day-in-life', 'asset-20-month-in-life', 'asset-21-user-journey-maps']::TEXT[],
  22, -- Personalization depth = asset number
  'sub_11_2',
  25,
  22,
  true
);

-- Asset 23: Ideal Head of Sales Profile
INSERT INTO resources (
  resource_code, asset_number, name, description, tier,
  strategic_prompts, implementation_guides,
  generation_time_minutes, consulting_equivalent_usd,
  requires_context_from, personalization_depth,
  unlock_milestone_code, unlock_threshold_percentage,
  display_order, is_active
) VALUES (
  'asset-23-ideal-head-of-sales',
  23,
  'Ideal Head of Sales Profile',
  'Define the perfect sales leader for your stage',
  'growth',
  '["ideal-head-of-sales"]'::jsonb,
  '["job-description","interview-questions","onboarding-plan"]'::jsonb,
  12,
  10000,
  ARRAY['asset-1-icp-analysis', 'asset-2-target-buyer-personas', 'asset-3-empathy-maps', 'asset-4-icp-rating-system', 'asset-5-buyer-persona-rating', 'asset-6-negative-buyer-personas', 'asset-7-pmf-assessment', 'asset-8-product-potential-assessment', 'asset-9-refined-product-description', 'asset-10-technical-sales-translator', 'asset-11-value-messaging', 'asset-12-cost-of-inaction-calculator', 'asset-13-compelling-events', 'asset-14-sales-slide-deck', 'asset-15-buying-committee-navigation-guide', 'asset-16-stakeholder-arsenal', 'asset-17-mock-selling-dialogues', 'asset-18-mock-selling-dialogues', 'asset-19-day-in-life', 'asset-20-month-in-life', 'asset-21-user-journey-maps', 'asset-22-buyer-ux-considerations']::TEXT[],
  23, -- Personalization depth = asset number
  'sub_11_2',
  50,
  23,
  true
);

-- Asset 24: Problem Validation Survey
INSERT INTO resources (
  resource_code, asset_number, name, description, tier,
  strategic_prompts, implementation_guides,
  generation_time_minutes, consulting_equivalent_usd,
  requires_context_from, personalization_depth,
  unlock_milestone_code, unlock_threshold_percentage,
  display_order, is_active
) VALUES (
  'asset-24-mock-problem-validation',
  24,
  'Problem Validation Survey',
  'Validate customer pain points and willingness to pay',
  'growth',
  '["mock-problem-validation"]'::jsonb,
  '["survey-execution-plan","willingness-to-pay-analysis"]'::jsonb,
  10,
  8000,
  ARRAY['asset-1-icp-analysis', 'asset-2-target-buyer-personas', 'asset-3-empathy-maps', 'asset-4-icp-rating-system', 'asset-5-buyer-persona-rating', 'asset-6-negative-buyer-personas', 'asset-7-pmf-assessment', 'asset-8-product-potential-assessment', 'asset-9-refined-product-description', 'asset-10-technical-sales-translator', 'asset-11-value-messaging', 'asset-12-cost-of-inaction-calculator', 'asset-13-compelling-events', 'asset-14-sales-slide-deck', 'asset-15-buying-committee-navigation-guide', 'asset-16-stakeholder-arsenal', 'asset-17-mock-selling-dialogues', 'asset-18-mock-selling-dialogues', 'asset-19-day-in-life', 'asset-20-month-in-life', 'asset-21-user-journey-maps', 'asset-22-buyer-ux-considerations', 'asset-23-ideal-head-of-sales']::TEXT[],
  24, -- Personalization depth = asset number
  'sub_11_2',
  75,
  24,
  true
);

-- Asset 25: Product Usage Assessment
INSERT INTO resources (
  resource_code, asset_number, name, description, tier,
  strategic_prompts, implementation_guides,
  generation_time_minutes, consulting_equivalent_usd,
  requires_context_from, personalization_depth,
  unlock_milestone_code, unlock_threshold_percentage,
  display_order, is_active
) VALUES (
  'asset-25-product-usage-assessments',
  25,
  'Product Usage Assessment',
  'Analyze adoption patterns and usage optimization',
  'growth',
  '["product-usage-assessments","product-usage-timing-assessment"]'::jsonb,
  '["onboarding-sequence","usage-barrier-mitigation"]'::jsonb,
  12,
  9000,
  ARRAY['asset-1-icp-analysis', 'asset-2-target-buyer-personas', 'asset-3-empathy-maps', 'asset-4-icp-rating-system', 'asset-5-buyer-persona-rating', 'asset-6-negative-buyer-personas', 'asset-7-pmf-assessment', 'asset-8-product-potential-assessment', 'asset-9-refined-product-description', 'asset-10-technical-sales-translator', 'asset-11-value-messaging', 'asset-12-cost-of-inaction-calculator', 'asset-13-compelling-events', 'asset-14-sales-slide-deck', 'asset-15-buying-committee-navigation-guide', 'asset-16-stakeholder-arsenal', 'asset-17-mock-selling-dialogues', 'asset-18-mock-selling-dialogues', 'asset-19-day-in-life', 'asset-20-month-in-life', 'asset-21-user-journey-maps', 'asset-22-buyer-ux-considerations', 'asset-23-ideal-head-of-sales', 'asset-24-mock-problem-validation']::TEXT[],
  25, -- Personalization depth = asset number
  'sub_11_3',
  25,
  25,
  true
);

-- Asset 26: Detailed Service Prototype
INSERT INTO resources (
  resource_code, asset_number, name, description, tier,
  strategic_prompts, implementation_guides,
  generation_time_minutes, consulting_equivalent_usd,
  requires_context_from, personalization_depth,
  unlock_milestone_code, unlock_threshold_percentage,
  display_order, is_active
) VALUES (
  'asset-26-detailed-service-prototype',
  26,
  'Detailed Service Prototype',
  'Design and test service delivery models',
  'growth',
  '["detailed-service-prototype"]'::jsonb,
  '["service-design-implementation","customer-testing-plan"]'::jsonb,
  12,
  10000,
  ARRAY['asset-1-icp-analysis', 'asset-2-target-buyer-personas', 'asset-3-empathy-maps', 'asset-4-icp-rating-system', 'asset-5-buyer-persona-rating', 'asset-6-negative-buyer-personas', 'asset-7-pmf-assessment', 'asset-8-product-potential-assessment', 'asset-9-refined-product-description', 'asset-10-technical-sales-translator', 'asset-11-value-messaging', 'asset-12-cost-of-inaction-calculator', 'asset-13-compelling-events', 'asset-14-sales-slide-deck', 'asset-15-buying-committee-navigation-guide', 'asset-16-stakeholder-arsenal', 'asset-17-mock-selling-dialogues', 'asset-18-mock-selling-dialogues', 'asset-19-day-in-life', 'asset-20-month-in-life', 'asset-21-user-journey-maps', 'asset-22-buyer-ux-considerations', 'asset-23-ideal-head-of-sales', 'asset-24-mock-problem-validation', 'asset-25-product-usage-assessments']::TEXT[],
  26, -- Personalization depth = asset number
  'sub_11_3',
  50,
  26,
  true
);

-- Asset 27: Persona-Based Prototyping
INSERT INTO resources (
  resource_code, asset_number, name, description, tier,
  strategic_prompts, implementation_guides,
  generation_time_minutes, consulting_equivalent_usd,
  requires_context_from, personalization_depth,
  unlock_milestone_code, unlock_threshold_percentage,
  display_order, is_active
) VALUES (
  'asset-27-persona-based-prototyping',
  27,
  'Persona-Based Prototyping',
  'Test product variations with specific buyer personas',
  'growth',
  '["persona-based-prototyping"]'::jsonb,
  '["prototype-validation-testing","iteration-framework"]'::jsonb,
  10,
  8000,
  ARRAY['asset-1-icp-analysis', 'asset-2-target-buyer-personas', 'asset-3-empathy-maps', 'asset-4-icp-rating-system', 'asset-5-buyer-persona-rating', 'asset-6-negative-buyer-personas', 'asset-7-pmf-assessment', 'asset-8-product-potential-assessment', 'asset-9-refined-product-description', 'asset-10-technical-sales-translator', 'asset-11-value-messaging', 'asset-12-cost-of-inaction-calculator', 'asset-13-compelling-events', 'asset-14-sales-slide-deck', 'asset-15-buying-committee-navigation-guide', 'asset-16-stakeholder-arsenal', 'asset-17-mock-selling-dialogues', 'asset-18-mock-selling-dialogues', 'asset-19-day-in-life', 'asset-20-month-in-life', 'asset-21-user-journey-maps', 'asset-22-buyer-ux-considerations', 'asset-23-ideal-head-of-sales', 'asset-24-mock-problem-validation', 'asset-25-product-usage-assessments', 'asset-26-detailed-service-prototype']::TEXT[],
  27, -- Personalization depth = asset number
  'sub_11_3',
  75,
  27,
  true
);

-- Asset 28: Sales Tasks Advanced
INSERT INTO resources (
  resource_code, asset_number, name, description, tier,
  strategic_prompts, implementation_guides,
  generation_time_minutes, consulting_equivalent_usd,
  requires_context_from, personalization_depth,
  unlock_milestone_code, unlock_threshold_percentage,
  display_order, is_active
) VALUES (
  'asset-28-sales-tasks-basic',
  28,
  'Sales Tasks Advanced',
  'Optimize sales operations and time management',
  'growth',
  '["sales-tasks-basic","sales-tasks-advanced"]'::jsonb,
  '["calendar-blocking-plan","delegation-automation-matrix"]'::jsonb,
  12,
  9000,
  ARRAY['asset-1-icp-analysis', 'asset-2-target-buyer-personas', 'asset-3-empathy-maps', 'asset-4-icp-rating-system', 'asset-5-buyer-persona-rating', 'asset-6-negative-buyer-personas', 'asset-7-pmf-assessment', 'asset-8-product-potential-assessment', 'asset-9-refined-product-description', 'asset-10-technical-sales-translator', 'asset-11-value-messaging', 'asset-12-cost-of-inaction-calculator', 'asset-13-compelling-events', 'asset-14-sales-slide-deck', 'asset-15-buying-committee-navigation-guide', 'asset-16-stakeholder-arsenal', 'asset-17-mock-selling-dialogues', 'asset-18-mock-selling-dialogues', 'asset-19-day-in-life', 'asset-20-month-in-life', 'asset-21-user-journey-maps', 'asset-22-buyer-ux-considerations', 'asset-23-ideal-head-of-sales', 'asset-24-mock-problem-validation', 'asset-25-product-usage-assessments', 'asset-26-detailed-service-prototype', 'asset-27-persona-based-prototyping']::TEXT[],
  28, -- Personalization depth = asset number
  'sub_12_1',
  25,
  28,
  true
);

-- Asset 29: Executive Business Case Builder
INSERT INTO resources (
  resource_code, asset_number, name, description, tier,
  strategic_prompts, implementation_guides,
  generation_time_minutes, consulting_equivalent_usd,
  requires_context_from, personalization_depth,
  unlock_milestone_code, unlock_threshold_percentage,
  display_order, is_active
) VALUES (
  'asset-29-executive-business-case',
  29,
  'Executive Business Case Builder',
  'Create C-level presentations that drive decisions',
  'enterprise',
  '["executive-business-case"]'::jsonb,
  '["personalized-business-cases","review-process"]'::jsonb,
  15,
  15000,
  ARRAY['asset-1-icp-analysis', 'asset-2-target-buyer-personas', 'asset-3-empathy-maps', 'asset-4-icp-rating-system', 'asset-5-buyer-persona-rating', 'asset-6-negative-buyer-personas', 'asset-7-pmf-assessment', 'asset-8-product-potential-assessment', 'asset-9-refined-product-description', 'asset-10-technical-sales-translator', 'asset-11-value-messaging', 'asset-12-cost-of-inaction-calculator', 'asset-13-compelling-events', 'asset-14-sales-slide-deck', 'asset-15-buying-committee-navigation-guide', 'asset-16-stakeholder-arsenal', 'asset-17-mock-selling-dialogues', 'asset-18-mock-selling-dialogues', 'asset-19-day-in-life', 'asset-20-month-in-life', 'asset-21-user-journey-maps', 'asset-22-buyer-ux-considerations', 'asset-23-ideal-head-of-sales', 'asset-24-mock-problem-validation', 'asset-25-product-usage-assessments', 'asset-26-detailed-service-prototype', 'asset-27-persona-based-prototyping', 'asset-28-sales-tasks-basic']::TEXT[],
  29, -- Personalization depth = asset number
  'sub_12_2',
  25,
  29,
  true
);

-- Asset 30: Board Presentation Framework
INSERT INTO resources (
  resource_code, asset_number, name, description, tier,
  strategic_prompts, implementation_guides,
  generation_time_minutes, consulting_equivalent_usd,
  requires_context_from, personalization_depth,
  unlock_milestone_code, unlock_threshold_percentage,
  display_order, is_active
) VALUES (
  'asset-30-board-presentation',
  30,
  'Board Presentation Framework',
  'Present to boards and executive committees effectively',
  'enterprise',
  '["board-presentation"]'::jsonb,
  '["investor-ready-slides","pitch-deck-integration"]'::jsonb,
  15,
  18000,
  ARRAY['asset-1-icp-analysis', 'asset-2-target-buyer-personas', 'asset-3-empathy-maps', 'asset-4-icp-rating-system', 'asset-5-buyer-persona-rating', 'asset-6-negative-buyer-personas', 'asset-7-pmf-assessment', 'asset-8-product-potential-assessment', 'asset-9-refined-product-description', 'asset-10-technical-sales-translator', 'asset-11-value-messaging', 'asset-12-cost-of-inaction-calculator', 'asset-13-compelling-events', 'asset-14-sales-slide-deck', 'asset-15-buying-committee-navigation-guide', 'asset-16-stakeholder-arsenal', 'asset-17-mock-selling-dialogues', 'asset-18-mock-selling-dialogues', 'asset-19-day-in-life', 'asset-20-month-in-life', 'asset-21-user-journey-maps', 'asset-22-buyer-ux-considerations', 'asset-23-ideal-head-of-sales', 'asset-24-mock-problem-validation', 'asset-25-product-usage-assessments', 'asset-26-detailed-service-prototype', 'asset-27-persona-based-prototyping', 'asset-28-sales-tasks-basic', 'asset-29-executive-business-case']::TEXT[],
  30, -- Personalization depth = asset number
  'sub_12_3',
  25,
  30,
  true
);

-- Asset 31: Series B Readiness Assessment
INSERT INTO resources (
  resource_code, asset_number, name, description, tier,
  strategic_prompts, implementation_guides,
  generation_time_minutes, consulting_equivalent_usd,
  requires_context_from, personalization_depth,
  unlock_milestone_code, unlock_threshold_percentage,
  display_order, is_active
) VALUES (
  'asset-31-series-b-readiness',
  31,
  'Series B Readiness Assessment',
  'Evaluate fundraising readiness and gaps',
  'enterprise',
  '["series-b-readiness"]'::jsonb,
  '["funding-prep-checklist","investor-outreach-plan"]'::jsonb,
  12,
  12000,
  ARRAY['asset-1-icp-analysis', 'asset-2-target-buyer-personas', 'asset-3-empathy-maps', 'asset-4-icp-rating-system', 'asset-5-buyer-persona-rating', 'asset-6-negative-buyer-personas', 'asset-7-pmf-assessment', 'asset-8-product-potential-assessment', 'asset-9-refined-product-description', 'asset-10-technical-sales-translator', 'asset-11-value-messaging', 'asset-12-cost-of-inaction-calculator', 'asset-13-compelling-events', 'asset-14-sales-slide-deck', 'asset-15-buying-committee-navigation-guide', 'asset-16-stakeholder-arsenal', 'asset-17-mock-selling-dialogues', 'asset-18-mock-selling-dialogues', 'asset-19-day-in-life', 'asset-20-month-in-life', 'asset-21-user-journey-maps', 'asset-22-buyer-ux-considerations', 'asset-23-ideal-head-of-sales', 'asset-24-mock-problem-validation', 'asset-25-product-usage-assessments', 'asset-26-detailed-service-prototype', 'asset-27-persona-based-prototyping', 'asset-28-sales-tasks-basic', 'asset-29-executive-business-case', 'asset-30-board-presentation']::TEXT[],
  31, -- Personalization depth = asset number
  'sub_13_1',
  25,
  31,
  true
);

-- Asset 32: Ideal Investor Profile
INSERT INTO resources (
  resource_code, asset_number, name, description, tier,
  strategic_prompts, implementation_guides,
  generation_time_minutes, consulting_equivalent_usd,
  requires_context_from, personalization_depth,
  unlock_milestone_code, unlock_threshold_percentage,
  display_order, is_active
) VALUES (
  'asset-32-ideal-investor-profile',
  32,
  'Ideal Investor Profile',
  'Target the right VCs for your specific company',
  'enterprise',
  '["ideal-investor-profile"]'::jsonb,
  '["investor-target-list","outreach-strategy"]'::jsonb,
  10,
  10000,
  ARRAY['asset-1-icp-analysis', 'asset-2-target-buyer-personas', 'asset-3-empathy-maps', 'asset-4-icp-rating-system', 'asset-5-buyer-persona-rating', 'asset-6-negative-buyer-personas', 'asset-7-pmf-assessment', 'asset-8-product-potential-assessment', 'asset-9-refined-product-description', 'asset-10-technical-sales-translator', 'asset-11-value-messaging', 'asset-12-cost-of-inaction-calculator', 'asset-13-compelling-events', 'asset-14-sales-slide-deck', 'asset-15-buying-committee-navigation-guide', 'asset-16-stakeholder-arsenal', 'asset-17-mock-selling-dialogues', 'asset-18-mock-selling-dialogues', 'asset-19-day-in-life', 'asset-20-month-in-life', 'asset-21-user-journey-maps', 'asset-22-buyer-ux-considerations', 'asset-23-ideal-head-of-sales', 'asset-24-mock-problem-validation', 'asset-25-product-usage-assessments', 'asset-26-detailed-service-prototype', 'asset-27-persona-based-prototyping', 'asset-28-sales-tasks-basic', 'asset-29-executive-business-case', 'asset-30-board-presentation', 'asset-31-series-b-readiness']::TEXT[],
  32, -- Personalization depth = asset number
  'sub_13_2',
  25,
  32,
  true
);

-- Asset 33: Advanced ROI Models
INSERT INTO resources (
  resource_code, asset_number, name, description, tier,
  strategic_prompts, implementation_guides,
  generation_time_minutes, consulting_equivalent_usd,
  requires_context_from, personalization_depth,
  unlock_milestone_code, unlock_threshold_percentage,
  display_order, is_active
) VALUES (
  'asset-33-roi-models',
  33,
  'Advanced ROI Models',
  'Sophisticated financial impact modeling',
  'enterprise',
  '["roi-models"]'::jsonb,
  '["multi-scenario-calculators","executive-presentation"]'::jsonb,
  15,
  14000,
  ARRAY['asset-1-icp-analysis', 'asset-2-target-buyer-personas', 'asset-3-empathy-maps', 'asset-4-icp-rating-system', 'asset-5-buyer-persona-rating', 'asset-6-negative-buyer-personas', 'asset-7-pmf-assessment', 'asset-8-product-potential-assessment', 'asset-9-refined-product-description', 'asset-10-technical-sales-translator', 'asset-11-value-messaging', 'asset-12-cost-of-inaction-calculator', 'asset-13-compelling-events', 'asset-14-sales-slide-deck', 'asset-15-buying-committee-navigation-guide', 'asset-16-stakeholder-arsenal', 'asset-17-mock-selling-dialogues', 'asset-18-mock-selling-dialogues', 'asset-19-day-in-life', 'asset-20-month-in-life', 'asset-21-user-journey-maps', 'asset-22-buyer-ux-considerations', 'asset-23-ideal-head-of-sales', 'asset-24-mock-problem-validation', 'asset-25-product-usage-assessments', 'asset-26-detailed-service-prototype', 'asset-27-persona-based-prototyping', 'asset-28-sales-tasks-basic', 'asset-29-executive-business-case', 'asset-30-board-presentation', 'asset-31-series-b-readiness', 'asset-32-ideal-investor-profile']::TEXT[],
  33, -- Personalization depth = asset number
  'sub_13_3',
  25,
  33,
  true
);

-- Asset 34: Scenario Planning Framework
INSERT INTO resources (
  resource_code, asset_number, name, description, tier,
  strategic_prompts, implementation_guides,
  generation_time_minutes, consulting_equivalent_usd,
  requires_context_from, personalization_depth,
  unlock_milestone_code, unlock_threshold_percentage,
  display_order, is_active
) VALUES (
  'asset-34-scenario-planning',
  34,
  'Scenario Planning Framework',
  'Model strategic options and future paths',
  'enterprise',
  '["scenario-planning"]'::jsonb,
  '["strategic-options-analysis","decision-matrix"]'::jsonb,
  12,
  13000,
  ARRAY['asset-1-icp-analysis', 'asset-2-target-buyer-personas', 'asset-3-empathy-maps', 'asset-4-icp-rating-system', 'asset-5-buyer-persona-rating', 'asset-6-negative-buyer-personas', 'asset-7-pmf-assessment', 'asset-8-product-potential-assessment', 'asset-9-refined-product-description', 'asset-10-technical-sales-translator', 'asset-11-value-messaging', 'asset-12-cost-of-inaction-calculator', 'asset-13-compelling-events', 'asset-14-sales-slide-deck', 'asset-15-buying-committee-navigation-guide', 'asset-16-stakeholder-arsenal', 'asset-17-mock-selling-dialogues', 'asset-18-mock-selling-dialogues', 'asset-19-day-in-life', 'asset-20-month-in-life', 'asset-21-user-journey-maps', 'asset-22-buyer-ux-considerations', 'asset-23-ideal-head-of-sales', 'asset-24-mock-problem-validation', 'asset-25-product-usage-assessments', 'asset-26-detailed-service-prototype', 'asset-27-persona-based-prototyping', 'asset-28-sales-tasks-basic', 'asset-29-executive-business-case', 'asset-30-board-presentation', 'asset-31-series-b-readiness', 'asset-32-ideal-investor-profile', 'asset-33-roi-models']::TEXT[],
  34, -- Personalization depth = asset number
  'sub_14_1',
  25,
  34,
  true
);

-- Asset 35: Service Blueprints
INSERT INTO resources (
  resource_code, asset_number, name, description, tier,
  strategic_prompts, implementation_guides,
  generation_time_minutes, consulting_equivalent_usd,
  requires_context_from, personalization_depth,
  unlock_milestone_code, unlock_threshold_percentage,
  display_order, is_active
) VALUES (
  'asset-35-service-blueprints',
  35,
  'Service Blueprints',
  'Map and optimize service delivery processes',
  'enterprise',
  '["service-blueprints","service-fmea"]'::jsonb,
  '["process-mapping","failure-mode-analysis","optimization-plan"]'::jsonb,
  15,
  16000,
  ARRAY['asset-1-icp-analysis', 'asset-2-target-buyer-personas', 'asset-3-empathy-maps', 'asset-4-icp-rating-system', 'asset-5-buyer-persona-rating', 'asset-6-negative-buyer-personas', 'asset-7-pmf-assessment', 'asset-8-product-potential-assessment', 'asset-9-refined-product-description', 'asset-10-technical-sales-translator', 'asset-11-value-messaging', 'asset-12-cost-of-inaction-calculator', 'asset-13-compelling-events', 'asset-14-sales-slide-deck', 'asset-15-buying-committee-navigation-guide', 'asset-16-stakeholder-arsenal', 'asset-17-mock-selling-dialogues', 'asset-18-mock-selling-dialogues', 'asset-19-day-in-life', 'asset-20-month-in-life', 'asset-21-user-journey-maps', 'asset-22-buyer-ux-considerations', 'asset-23-ideal-head-of-sales', 'asset-24-mock-problem-validation', 'asset-25-product-usage-assessments', 'asset-26-detailed-service-prototype', 'asset-27-persona-based-prototyping', 'asset-28-sales-tasks-basic', 'asset-29-executive-business-case', 'asset-30-board-presentation', 'asset-31-series-b-readiness', 'asset-32-ideal-investor-profile', 'asset-33-roi-models', 'asset-34-scenario-planning']::TEXT[],
  35, -- Personalization depth = asset number
  'sub_14_1',
  50,
  35,
  true
);

-- Asset 36: Backstage Process Optimization
INSERT INTO resources (
  resource_code, asset_number, name, description, tier,
  strategic_prompts, implementation_guides,
  generation_time_minutes, consulting_equivalent_usd,
  requires_context_from, personalization_depth,
  unlock_milestone_code, unlock_threshold_percentage,
  display_order, is_active
) VALUES (
  'asset-36-backstage-process-optimization',
  36,
  'Backstage Process Optimization',
  'Improve internal operations and efficiency',
  'enterprise',
  '["backstage-process-optimization"]'::jsonb,
  '["process-audit","efficiency-improvement-plan"]'::jsonb,
  12,
  11000,
  ARRAY['asset-1-icp-analysis', 'asset-2-target-buyer-personas', 'asset-3-empathy-maps', 'asset-4-icp-rating-system', 'asset-5-buyer-persona-rating', 'asset-6-negative-buyer-personas', 'asset-7-pmf-assessment', 'asset-8-product-potential-assessment', 'asset-9-refined-product-description', 'asset-10-technical-sales-translator', 'asset-11-value-messaging', 'asset-12-cost-of-inaction-calculator', 'asset-13-compelling-events', 'asset-14-sales-slide-deck', 'asset-15-buying-committee-navigation-guide', 'asset-16-stakeholder-arsenal', 'asset-17-mock-selling-dialogues', 'asset-18-mock-selling-dialogues', 'asset-19-day-in-life', 'asset-20-month-in-life', 'asset-21-user-journey-maps', 'asset-22-buyer-ux-considerations', 'asset-23-ideal-head-of-sales', 'asset-24-mock-problem-validation', 'asset-25-product-usage-assessments', 'asset-26-detailed-service-prototype', 'asset-27-persona-based-prototyping', 'asset-28-sales-tasks-basic', 'asset-29-executive-business-case', 'asset-30-board-presentation', 'asset-31-series-b-readiness', 'asset-32-ideal-investor-profile', 'asset-33-roi-models', 'asset-34-scenario-planning', 'asset-35-service-blueprints']::TEXT[],
  36, -- Personalization depth = asset number
  'sub_14_2',
  25,
  36,
  true
);

-- Asset 37: Jobs-to-Be-Done Framework
INSERT INTO resources (
  resource_code, asset_number, name, description, tier,
  strategic_prompts, implementation_guides,
  generation_time_minutes, consulting_equivalent_usd,
  requires_context_from, personalization_depth,
  unlock_milestone_code, unlock_threshold_percentage,
  display_order, is_active
) VALUES (
  'asset-37-jobs-to-be-done',
  37,
  'Jobs-to-Be-Done Framework',
  'Understand customer motivation and outcomes',
  'enterprise',
  '["jobs-to-be-done"]'::jsonb,
  '["messaging-reframe","success-metrics-definition"]'::jsonb,
  10,
  9000,
  ARRAY['asset-1-icp-analysis', 'asset-2-target-buyer-personas', 'asset-3-empathy-maps', 'asset-4-icp-rating-system', 'asset-5-buyer-persona-rating', 'asset-6-negative-buyer-personas', 'asset-7-pmf-assessment', 'asset-8-product-potential-assessment', 'asset-9-refined-product-description', 'asset-10-technical-sales-translator', 'asset-11-value-messaging', 'asset-12-cost-of-inaction-calculator', 'asset-13-compelling-events', 'asset-14-sales-slide-deck', 'asset-15-buying-committee-navigation-guide', 'asset-16-stakeholder-arsenal', 'asset-17-mock-selling-dialogues', 'asset-18-mock-selling-dialogues', 'asset-19-day-in-life', 'asset-20-month-in-life', 'asset-21-user-journey-maps', 'asset-22-buyer-ux-considerations', 'asset-23-ideal-head-of-sales', 'asset-24-mock-problem-validation', 'asset-25-product-usage-assessments', 'asset-26-detailed-service-prototype', 'asset-27-persona-based-prototyping', 'asset-28-sales-tasks-basic', 'asset-29-executive-business-case', 'asset-30-board-presentation', 'asset-31-series-b-readiness', 'asset-32-ideal-investor-profile', 'asset-33-roi-models', 'asset-34-scenario-planning', 'asset-35-service-blueprints', 'asset-36-backstage-process-optimization']::TEXT[],
  37, -- Personalization depth = asset number
  'sub_14_2',
  50,
  37,
  true
);

-- Asset 38: Systems Interactions Map
INSERT INTO resources (
  resource_code, asset_number, name, description, tier,
  strategic_prompts, implementation_guides,
  generation_time_minutes, consulting_equivalent_usd,
  requires_context_from, personalization_depth,
  unlock_milestone_code, unlock_threshold_percentage,
  display_order, is_active
) VALUES (
  'asset-38-systems-interactions-map',
  38,
  'Systems Interactions Map',
  'Visualize technical and business system integrations',
  'enterprise',
  '["systems-interactions-map"]'::jsonb,
  '["integration-architecture","technical-documentation"]'::jsonb,
  12,
  10000,
  ARRAY['asset-1-icp-analysis', 'asset-2-target-buyer-personas', 'asset-3-empathy-maps', 'asset-4-icp-rating-system', 'asset-5-buyer-persona-rating', 'asset-6-negative-buyer-personas', 'asset-7-pmf-assessment', 'asset-8-product-potential-assessment', 'asset-9-refined-product-description', 'asset-10-technical-sales-translator', 'asset-11-value-messaging', 'asset-12-cost-of-inaction-calculator', 'asset-13-compelling-events', 'asset-14-sales-slide-deck', 'asset-15-buying-committee-navigation-guide', 'asset-16-stakeholder-arsenal', 'asset-17-mock-selling-dialogues', 'asset-18-mock-selling-dialogues', 'asset-19-day-in-life', 'asset-20-month-in-life', 'asset-21-user-journey-maps', 'asset-22-buyer-ux-considerations', 'asset-23-ideal-head-of-sales', 'asset-24-mock-problem-validation', 'asset-25-product-usage-assessments', 'asset-26-detailed-service-prototype', 'asset-27-persona-based-prototyping', 'asset-28-sales-tasks-basic', 'asset-29-executive-business-case', 'asset-30-board-presentation', 'asset-31-series-b-readiness', 'asset-32-ideal-investor-profile', 'asset-33-roi-models', 'asset-34-scenario-planning', 'asset-35-service-blueprints', 'asset-36-backstage-process-optimization', 'asset-37-jobs-to-be-done']::TEXT[],
  38, -- Personalization depth = asset number
  'sub_14_3',
  100,
  38,
  true
);

-- ===============================================
-- SEED COMPLETE
-- ===============================================
-- Total assets seeded: 38
-- Foundation tier: 14 assets
-- Growth tier: 14 assets
-- Enterprise tier: 10 assets
-- ===============================================
